<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="Nasrin_1988" failures="2" tests="2" name="Test(failed)(failed)" time="0.035" errors="0" timestamp="17 May 2023 08:12:57 GMT">
  <testcase classname="com.TestNGChallenges.FailedTesting" name="getTestOne" time="0.01">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.TestNGChallenges.FailedTesting.getTestOne(FailedTesting.java:11)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- getTestOne -->
  <testcase classname="com.TestNGChallenges.FailedTesting" name="getTestFive" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.TestNGChallenges.FailedTesting.getTestFive(FailedTesting.java:38)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- getTestFive -->
  <testcase classname="com.TestNGChallenges.FailedTesting" name="getTestThree" time="0.0">
    <ignored/>
  </testcase> <!-- getTestThree -->
  <testcase classname="com.TestNGChallenges.FailedTesting" name="getTestFour" time="0.0">
    <ignored/>
  </testcase> <!-- getTestFour -->
  <testcase classname="com.TestNGChallenges.FailedTesting" name="getTestTwo" time="0.0">
    <ignored/>
  </testcase> <!-- getTestTwo -->
</testsuite> <!-- Test(failed)(failed) -->
